- text: Task
  icon: 
  url: settings/task.html

- text: Department
  icon: 
  url: settings/department.html

- text: Template
  icon: 
  url: settings/template.html

- text: Tutorial
  icon: 
  url: settings/tutorial.html
